"""empty message

Revision ID: 94a5f4025636
Revises: 12ee0fb59417
Create Date: 2024-11-07 23:31:43.675710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a5f4025636'
down_revision = '12ee0fb59417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)

    # ### end Alembic commands ###
